name: ci

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    concurrency:
      group: ${{ github.ref_name != 'main' && format('{0}-{1}', github.workflow, github.ref) || github.sha }}
      cancel-in-progress: ${{ github.ref_name != 'main' }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev-2024-12

      - name: Build desktop
        run: make build-desktop-release

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.74
          actions-cache-folder: emsdk-cache

      - name: Build web
        run: make build-web-release
